/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.catolicasc.foodtruck.change;

import com.catolicasc.foodtruck.models.Ordered;
import com.catolicasc.foodtruck.repositories.OrderedRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class AddEditOrdered extends javax.swing.JInternalFrame {

    private OrderedRepository orderedRepository = new OrderedRepository();
    
    private Ordered ordered;
    
    private void updateScreen(Ordered ordered) {
        tfID.setText(ordered.getId().toString());
        tfQuantity.setText(ordered.getQuantity());
        tfProduct_id.setText(ordered.getProduct_id());
        tfOrder_id.setText(ordered.getOrder_id());
        tfUnit_price.setText(ordered.getUnit_price());
    }
    
    /**
     * Creates new form AddEditOrdered
     */
    public AddEditOrdered() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
    }                                        

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {                                       
        try {
            Double quantity = tfQuantity.getText();
            Long product_id = tfProduct_id.getText();
            Long order_id = tfOrder_id.getText();
            Double unit_price = tfUnit_price.getText();
            
            if (ordered == null) {
                ordered = new Ordered();
                ordered.setQuantity(quantity);
                ordered.setProduct_id(product_id);
                ordered.setOrder_id(order_id);
                ordered.setUnit_price(unit_price);
                orderedRepository.add(ordered);
            } else {
                //Atualizar as propriedades do usuário
                //e fazer update do usuário no banco
            }
            
            
            updateScreen(ordered);
            
            JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
            
            this.dispose();
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um problema ao salvar");
        }
    }                                      

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {                                         
        if (ordered != null) {
            updateScreen(ordered);
        }
    }

    void setOrdered(Ordered ordered) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void Ordered(Ordered ordered) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
