/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.catolicasc.foodtruck.lists;

import com.catolicasc.foodtruck.change.AddEditProducts;
import com.catolicasc.foodtruck.models.Products;
import com.catolicasc.foodtruck.repositories.ProductsRepository;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brandon.kluck
 */

public class ListProducts extends javax.swing.JInternalFrame {

    private ProductsRepository productsRepository = new ProductsRepository();
    
    /**
     * Creates new form ListProducts
     */
    public ListProducts() {
        initComponents();
    }
    
    public void refreshProductsList() {
        DefaultTableModel tableModel = (DefaultTableModel) jtProducts.getModel();
        tableModel.setRowCount(0);
        
        ArrayList<Products> products = productsRepository.getAllProducts();
        
        for(Products product : products) {
            tableModel.addRow(new Object[] { 
                product.getId(),
                product.getDescription(),
                product.getPrice()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtProducts = new javax.swing.JTable();

        jtProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProducts.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtProducts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {                                      
        AddEditProducts addEditProducts = new AddEditProducts();
        this.getParent().add(addEditProducts);
        addEditProducts.setVisible(true);
    }                                     
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
        refreshProductsList();
    }                                        

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {                                          
        refreshProductsList();
    }                                         

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        if(jtProducts.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
            return;
        }
        
        Integer rowIndex = jtProducts.getSelectedRow();
        Integer productsId = (Integer) jtProducts.getModel().getValueAt(rowIndex, 0);
        
        Products products = productsRepository.getProductsById(productsId);
        
        AddEditProducts addEditProducts = new AddEditProducts();
        addEditProducts.setProducts(products);
        this.getParent().add(addEditProducts);
        addEditProducts.setVisible(true);
    }      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtProducts;
    // End of variables declaration//GEN-END:variables
}
